version: '3.0'
services:
  app:
    container_name: incubator-app
    image: incubator-app
    build: ./
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres:14
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_DB=incubator