version: '3.0'
services:
  app:
    container_name: incubator-app
    image: incubator-app
    build: ./
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgresqldb
      - redis
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_DB=incubator
  redis:
    image: redis/redis-stack-server
    ports:
        - "6379:6379"