server:
  port: ${PORT}

app:
  jwtSecret: ExLabADStartUpJWTSecret
  jwtExpirationMs: 86400000


spring:

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST}/incubator
    username: ${DB_USERNAME}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.mail.ru
    port: 465
    username: ad_incubator@mail.ru
    password: ${EMAIL_PASS}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 60000

    jedis:
      pool:
        config:
          maxTotal: 30
          minIdle: 10
          maxIdle: 20
          maxWaitMillis: 2000
          blockWhenExhausted: true
      save: 60 1 60 10
      appendfsync: everysec
      dir: /data