server:
  port: ${PORT}

app:
  jwtSecret: ExLabADStartUpJWTSecret
  jwtExpirationMs: 86400000


spring:

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/incubator
    username: ${DB_USERNAME}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.mail.ru
    port: 465
    username: ad_incubator@mail.ru
    password: ${EMAIL_PASS}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true


  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml